name: gsy_video_player
description: "GSYVideoPlayer is a video player for flutter.The video_player plugin support IJKplayer,ExoPlayer,MediaPlayer,AliPlayer"
version: 0.0.6
homepage: https://github.com/liuchuancong/gsy_video_player
repository: https://github.com/liuchuancong/gsy_video_player
documentation: https://github.com/CarGuo/GSYVideoPlayer

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  provider: ^6.1.2
  wakelock_plus: ^1.2.2
  sensors_plus: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.alizda.gsy_video_player
        pluginClass: GsyVideoPlayerPlugin

topics:
  - video-player